//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diaryinfo_tb
    {
        public int DiaryinfoID { get; set; }
        public Nullable<int> User_tbID { get; set; }
        public int Diarytype { get; set; }
        public string Diarycontent { get; set; }
        public string Diarymedia { get; set; }
        public System.DateTime Diarytime { get; set; }
    
        public virtual User_tb User_tb { get; set; }
    }
}
