//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_tb
    {
        public User_tb()
        {
            this.Diaryinfo_tb = new HashSet<Diaryinfo_tb>();
        }
    
        public int User_tbID { get; set; }
        public string Accountnumber { get; set; }
        public string Passwordr { get; set; }
        public System.DateTime Registertime { get; set; }
        public bool Memberstate { get; set; }
        public bool Accountstate { get; set; }
        public Nullable<System.DateTime> Memberopen { get; set; }
        public Nullable<System.DateTime> Memberover { get; set; }
    
        public virtual ICollection<Diaryinfo_tb> Diaryinfo_tb { get; set; }
    }
}
